# IONOS Deploy Now Konfiguration
# Für Static Site Generation (Astro)
# Hinweis: Diese Datei wird möglicherweise nicht verwendet,
# da der GitHub Workflow (.github/workflows/) die Deployment-Logik enthält

version: 1.0

deploy:
  # Build-Einstellungen
  build:
    # Node.js Version
    runtime: nodejs-22

    # Install-Befehl
    prepare:
      - npm ci

    # Build-Befehl
    build:
      - npm run build

    # Ausgabeverzeichnis (statische Dateien)
    dist: dist

  # Keine Runtime-Config nötig für Static Site
  # Die App läuft komplett client-seitig im Browser
