name: Deploy to Hetzner

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        env:
          PUBLIC_POCKETBASE_URL: ${{ secrets.PUBLIC_POCKETBASE_URL }}
        run: npm run build

      - name: Deploy to Hetzner via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USER }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/trainingsplaner-temp"
          strip_components: 1

      - name: Move files and restart services
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USER }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            # Backup alte Version
            if [ -d /var/www/trainingsplaner-backup ]; then
              rm -rf /var/www/trainingsplaner-backup
            fi
            if [ -d /var/www/trainingsplaner ]; then
              mv /var/www/trainingsplaner /var/www/trainingsplaner-backup
            fi

            # Neue Version aktivieren
            mv /var/www/trainingsplaner-temp /var/www/trainingsplaner
            chown -R www-data:www-data /var/www/trainingsplaner

            # Caddy neu laden (für neue Dateien)
            systemctl reload caddy

            echo "✅ Deployment erfolgreich!"
            echo "Deployed at: $(date)"
